
[project]
name = "payroll_extensions"
version = "1.0.0"
description = "Auto-calculates late entries, early exits, and extended leaves"
authors = [{ name = "WebAppick", email = "your@email.com" }]
dependencies = ["frappe"]

[tool.setuptools.packages.find]
where = ["payroll_extensions"]
