
[project]
name = "payroll-extensions"
version = "1.0.0"
description = "Auto-calculate late entries, early exits, and extended leaves"
authors = [{name = "Your Name", email = "you@example.com"}]
dependencies = ["frappe"]
dynamic = ["classifiers"]
